spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/criteriaresolverdemo
    username: postgres
    password: postgres
    initialization-mode: ALWAYS

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true